apiVersion: v1
kind: Secret
metadata:
  name: cluster-state-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: <forked-repo-url>
  password: <personal-access-token>
  username: oauth2
