apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/benjdauno/argo_demo'
    targetRevision: main
    path: cluster-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
