apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - {key: 'cert-manager-version', operator: Exists}
  template:
    metadata:
      name: cert-manager-{{name}}
    spec:
      project: default
      source:
        repoURL: https://charts.jetstack.io
        targetRevision: '{{metadata.labels.cert-manager-version}}'
        chart: cert-manager
        helm:
          valuesFiles:
            - configuration/cert-manager/default-values.yaml
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
